import type { Ticket } from '@kazaguruma/shared';
import { DEFAULT_PROJECT_ID } from './projects';

const NOW = '2026-04-29T03:00:00+09:00';

/**
 * 全 Ticket は デフォルト Project (Belvedere Core) 配下。
 * priority (緊急度) と valueImpact (プロダクトゴール貢献度) は独立した2軸。
 * 両者のミスマッチは Refinement Agent の検出対象 (例: WC-110 = priority=medium ∧ valueImpact=high)。
 */
export const seedTickets: Ticket[] = [
  {
    id: 'WC-101',
    projectId: DEFAULT_PROJECT_ID,
    title: 'プランニング会議の議事録テンプレ刷新',
    description: '前スプリントのプランニングで議事フォーマットがブレていた。DoD/SP/US紐付けが必須項目として埋まるテンプレに差し替える。',
    status: 'todo',
    priority: 'high',
    valueImpact: 'medium',
    ritual: 'planning',
    sprintId: 'sprint-13',
    assigneeId: 'kaede',
    estimatePt: 3,
    acceptanceCriteria: [
      'Notion/Markdownテンプレが用意されている',
      '前スプリントの3つのTryが冒頭に自動転記される',
      'Plannerエージェントが投稿できるフォーマット定義がある',
    ],
    labels: ['docs'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-102',
    projectId: DEFAULT_PROJECT_ID,
    title: 'デイリースクラム要約BotをSlackに常駐',
    description: 'デイリーAgentをSlackに常駐させ、開始5分前リマインドと終了後サマリを投稿する。',
    status: 'in-progress',
    priority: 'medium',
    valueImpact: 'medium',
    ritual: 'daily',
    sprintId: 'sprint-13',
    assigneeId: 'okubo',
    estimatePt: 5,
    acceptanceCriteria: [
      '#daily チャンネルに自動投稿される',
      '進捗ずれ・3日以上動きのないチケットを警告できる',
    ],
    labels: ['agent', 'slack'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-103',
    projectId: DEFAULT_PROJECT_ID,
    title: 'スプリントレビューのデモ環境をCloud Runに統一',
    description: 'PRごとのpreview revision URLを Reviewer Agent が発行し、レビュー時にステークホルダに送る。',
    status: 'review',
    priority: 'high',
    valueImpact: 'high',
    ritual: 'review',
    sprintId: 'sprint-13',
    assigneeId: 'hirai',
    estimatePt: 8,
    acceptanceCriteria: [
      'PRマージ前にCloud Run preview revisionが立ち上がる',
      'Reviewer AgentがURLを集約してSlackに投稿',
    ],
    labels: ['gcp', 'cloudrun'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-104',
    projectId: DEFAULT_PROJECT_ID,
    title: 'ふりかえりのTryを翌スプリントWIPに自動転記',
    description: 'Retrospective Agent がTryを抽出し、次スプリントのWIPチケットとして起票する。owner未指定の場合は人間に確認。',
    status: 'todo',
    priority: 'medium',
    valueImpact: 'high',
    ritual: 'retrospective',
    sprintId: 'sprint-13',
    assigneeId: 'uehara',
    estimatePt: 5,
    acceptanceCriteria: [
      'Tryがチケットとして翌スプリントに作られている',
      'parentTicketIdで元のTryと紐づく',
      'L2 (人間確認) のフローを通る',
    ],
    labels: ['agent', 'retrospective'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-105',
    projectId: DEFAULT_PROJECT_ID,
    title: 'チケット品質スコアのヘッダ常設化',
    description: 'バックログ全体の品質充足率 (DoD/SP/US紐付けが揃っているチケットの割合) を Web UI ヘッダに常時表示する。',
    status: 'in-progress',
    priority: 'urgent',
    valueImpact: 'high',
    ritual: 'planning',
    sprintId: 'sprint-13',
    assigneeId: 'kaede',
    estimatePt: 8,
    acceptanceCriteria: [
      'ヘッダーに常時表示される',
      '5分ごとに更新される',
      'クリックで内訳がドロップダウンする',
    ],
    labels: ['ui', 'quality'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-106',
    projectId: DEFAULT_PROJECT_ID,
    title: 'PRレビューLLMの誤検出を5%以下にチューニング',
    description: '前スプリントで10%まで下がった誤検出率を5%以下に。Eval setを増強しfew-shot+rubricで改善。',
    status: 'in-progress',
    priority: 'high',
    valueImpact: 'medium',
    ritual: 'daily',
    sprintId: 'sprint-13',
    assigneeId: 'hayashi',
    estimatePt: 13,
    acceptanceCriteria: [
      'Eval setが200件以上',
      '誤検出率 < 5% (信頼区間付き)',
      'コストはスプリント内で $50 以内',
    ],
    labels: ['llm', 'quality'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-107',
    projectId: DEFAULT_PROJECT_ID,
    title: 'ベロシティ計測を3スプリント移動平均に変更',
    description: '単発スプリントの数字に振り回されないため、ベロシティを直近3スプリントの移動平均で表示。',
    status: 'done',
    priority: 'medium',
    valueImpact: 'low',
    ritual: 'retrospective',
    sprintId: 'sprint-12',
    assigneeId: 'okubo',
    estimatePt: 3,
    acceptanceCriteria: [
      'ダッシュボードで移動平均が見える',
      '前スプリントの完了で数値が再計算される',
    ],
    labels: ['metrics'],
    createdAt: '2026-04-08T10:00:00+09:00',
    updatedAt: '2026-04-20T15:00:00+09:00',
    createdBy: 'agent:retrospective',
    parentTicketId: 'WC-RETRO-S11-T2',
  },
  {
    id: 'WC-108',
    projectId: DEFAULT_PROJECT_ID,
    title: 'Cloud Build → Cloud Deploy のパイプライン分離',
    description: 'ビルドとデプロイの責務分離。CB はイメージ作成まで、CD が dev → prod プロモーション。',
    status: 'backlog',
    priority: 'low',
    valueImpact: 'medium',
    ritual: 'daily',
    sprintId: 'sprint-14',
    assigneeId: 'hirai',
    estimatePt: 5,
    acceptanceCriteria: [
      'CB は Artifact Registry に image を push するだけ',
      'CD で dev → prod にプロモーションできる',
    ],
    labels: ['devops', 'gcp'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-109',
    projectId: DEFAULT_PROJECT_ID,
    title: 'スクラム形骸化の自動検出ルール v2',
    description: '儀式が形骸化している兆候 (出席率低下/onTime低下/Try未消化など) を検出し警告する。',
    status: 'todo',
    priority: 'high',
    valueImpact: 'high',
    ritual: 'planning',
    sprintId: 'sprint-13',
    assigneeId: 'uehara',
    estimatePt: 8,
    acceptanceCriteria: [
      'CeremonyHealthScore の複合条件でアラート',
      'Slackに「今、形骸化のサインが出ています」と通知',
      '誤検知率 < 10%',
    ],
    labels: ['differentiator'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-110',
    projectId: DEFAULT_PROJECT_ID,
    title: 'リリースゲートにOWASP Top 10自動チェック',
    description: 'CD のプロモーション直前に OWASP の自動チェックを通す。落ちたらリリース停止。',
    status: 'backlog',
    priority: 'medium',
    valueImpact: 'high',
    ritual: 'review',
    sprintId: 'sprint-14',
    assigneeId: 'hayashi',
    estimatePt: 8,
    acceptanceCriteria: [
      'Cloud Deploy のリリースゲートで実行',
      '違反時にレポートが Slack に投稿',
    ],
    labels: ['security', 'devops'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-111',
    projectId: DEFAULT_PROJECT_ID,
    title: 'ペアプロ音声をGeminiで要約しチケット化',
    description: 'ペアプロ中の音声を Speech-to-Text → Gemini 要約 → チケット化。L2で人間確認後保存。',
    status: 'in-progress',
    priority: 'low',
    valueImpact: 'low',
    ritual: 'daily',
    sprintId: 'sprint-13',
    assigneeId: 'kaede',
    estimatePt: 5,
    acceptanceCriteria: [
      '音声ファイル投入で要約とチケット候補が出る',
      '人間が承認するとチケット化される',
    ],
    labels: ['llm', 'audio'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
  {
    id: 'WC-112',
    projectId: DEFAULT_PROJECT_ID,
    title: '儀式健全性ダッシュボード公開',
    description: '儀式の健全性スコア (5儀式) を Web UI に公開。Sprint比較とトレンド線。',
    status: 'todo',
    priority: 'high',
    valueImpact: 'high',
    ritual: 'retrospective',
    sprintId: 'sprint-13',
    assigneeId: 'okubo',
    estimatePt: 13,
    acceptanceCriteria: [
      '5儀式のスコアが見える',
      '過去3スプリントのトレンドが見える',
      '低下時にRetrospective Agentが原因仮説を出す',
    ],
    labels: ['ui', 'dashboard'],
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'human',
  },
];
